### ISSUE TITLE
Support Guava's @VisibleForTesting annotation

### ISSUE THREAD

**Issue by OleksandrShkurat** [trubitsyn/VisibleForTesting#1]
It would be great to extend this plugin to support 
com.google.common.annotations.VisibleForTesting
annotation for Java projects. 
It will make your plugin useful not only for Android developers.

**Comment by trubitsyn** [comment]
Android Studio (but not IntelliJ) shows a warning when a public method annotated as `android.support.annotation.VisibleForTesting` is being accessed from main sources. But it does **not** work for `com.google.common.annotations.VisibleForTesting`. Will it still be useful? Just wondering what's a proper use case. I could make IntelliJ show a warning for that too, if you'd like.

**Comment by trubitsyn** [comment]
It actually does, inspection is disabled by default, I didn't notice. Will be implemented in 1.1.

**Comment by trubitsyn** [comment]
@AlexandrShkurat thank you for your suggestion! That greatly improved the plugin. Version 1.1.0 has just been released. You can get it [here](https://plugins.jetbrains.com/plugin/9952-visiblefortesting) or update if you have plugin installed. Please, let me know if you run into any issues.
