### ISSUE TITLE
Additional annotations support

### ISSUE THREAD

**Issue by OleksandrShkurat** [trubitsyn/VisibleForTesting#59]
I'd suggest this plugin supporting additional annotations:

- org.assertj.core.util.VisibleForTesting
- org.fest.util.VisibleForTesting

#1, #48

**Comment by trubitsyn** [comment]
Thanks for your suggestion!

**Comment by trubitsyn** [comment]
@OleksandrShkurat the new annotations have been made available in the `1.4.0` release. You can download it at the [Versions](https://plugins.jetbrains.com/plugin/9952-visiblefortesting/versions) page directly or update via IntelliJ (it might take some time for the new version to populate).

**Comment by OleksandrShkurat** [comment]
Awesome reaction speed. WOW. Thanks a lot!
